<a href="https://colab.research.google.com/github/panks11/CE888/blob/main/labs/lab6/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load the data from ``jester-data-1.csv'

In [57]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',header=None)

In [58]:
import numpy as np

In [59]:
df.shape

(24983, 101)

In [60]:
df.head()

0      1      2      3      4     5     6     7     8      9    ...    91   \
0   74  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  ...   2.82   
1  100   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88  ...   2.82   
2   49  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  ...  99.00   
3   48  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00  ...  99.00   
4   91   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44  ...   5.19   

     92     93     94     95     96     97     98     99     100  
0  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 101 columns]

Check the dataset description to figure out which value you should replace with NaNs (the cells for which we don't have a rating). This is the test set.

The ratings as '99' are to be replaced with NAN

Replace '99' in pandas dataframe with nan

In [61]:
df.replace(99,np.nan,inplace=True)

In [62]:
df.head()

0     1     2     3     4     5     6     7     8     9    ...   91   \
0   74.0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98  ...  2.82   
1  100.0  4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  ...  2.82   
2   49.0   NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN  ...   NaN   
3   48.0   NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  ...   NaN   
4   91.0  8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  ...  5.19   

    92    93    94    95    96    97    98    99    100  
0   NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1 -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2   NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4  5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  

[5 rows x 101 columns]

There's a column you need to remove because it doesn't contain ratings. Check the description of the dataset and figure out which one. Then drop it.

First column can be removed

In [63]:
df = df.iloc[:,1:]

In [64]:
arr = df.values
print(arr.shape)

(24983, 100)


Use pandas to find the best- and the worst-rated jokes

In [65]:
print("Worst Rated Joke ", np.argmin(df.mean(axis=0,skipna=True))+1, "with rating",np.min(df.mean(axis=0,skipna=True)))
print("Best Rated Joke ", np.argmax(df.mean(axis=0,skipna=True))+1, "with rating",np.max(df.mean(axis=0,skipna=True)))

Worst Rated Joke  58 with rating -3.8338796373689923
Best Rated Joke  50 with rating 3.6650848950824937


Modify and use the helper function provided in the helper_function notebook (or create your own) to label 10% of the dataset cells that are not NaNs as 99. This is your validation set. Keep the the actual values of the cells so you can use them later (as done in the example of the helper_function notebook)

## Labeling 10% of the dataset cells as NaNs (represented as 99 in our case) to create a validation set.

In [66]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(orig!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [67]:
new_arr, idx = replace(arr, 0.1)

In [68]:
arr[idx[0][0], idx[1][0]]

-8.79

In [69]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [70]:
new_arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan, 99.  ,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan, 99.  ,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43, 99.  , -3.98, ...,   nan,   nan,   nan]])

## latent factors modeling.

In [71]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [76]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=50):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if not np.isnan(rating) and rating!=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [77]:
sgd(iterations=10)

23.29225113253559


KeyboardInterrupt: ignored

In [74]:
predictions = latent_user_preferences.dot(latent_item_features.T)
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)

In [75]:
comparison_data

0                             1   \
0      (-7.82, 0.8854039464052083)     (8.79, 0.542454802753762)   
1      (4.08, 0.35397089062293685)  (-0.29, 0.22030427917628062)   
2        (nan, 2.2184119845608854)    (99.0, 1.3841458911253501)   
3        (nan, 0.5148593264066227)    (8.35, 0.3228687282619109)   
4        (8.5, 1.4384613006508449)    (4.61, 0.9131170142270633)   
...                            ...                           ...   
24978   (0.44, 1.5698110717319673)    (7.43, 0.9615978296434657)   
24979    (9.13, 0.886076223986561)   (-8.16, 0.5363633566780938)   
24980    (nan, 1.4377776001589946)    (99.0, 0.8895955463367774)   
24981     (nan, 1.351734271428575)     (nan, 0.8383761300616871)   
24982   (2.43, 1.6807414487490067)    (99.0, 1.0430732529190485)   

                                2                             3   \
0      (-9.66, 0.5230645945045923)  (-8.16, -0.5709951995852756)   
1      (6.36, 0.20948598991142559)  (4.37, -0.22005431401087763)   
2         (nan, 1.313268050657682)    (nan, -1.3708778646154849)   
3        (nan, 0.3049659925790862)    (nan, -0.3142640649359115)   
4      (-4.17, 0.8532405479203443)  (-5.39, -0.8515906770415962)   
...                            ...                           ...   
24978   (9.08, 0.9273692974106263)   (2.33, -1.0127703289339673)   
24979    (8.59, 0.522756798931172)    (9.08, -0.586973851084678)   
24980    (nan, 0.8503323491575018)    (nan, -0.9063725924431046)   
24981    (nan, 0.7996632524138858)     (nan, -0.847307006156585)   
24982  (-3.98, 0.9943676775311157)   (99.0, -1.0520099604764996)   

                                 4                            5   \
0        (99.0, 0.5556130265174153)    (-8.5, 1.485446054493778)   
1      (-2.38, 0.23252452186214906)  (-9.66, 0.5975464478122922)   
2        (9.03, 1.4677173265786096)   (9.27, 3.7486536416127203)   
3         (1.8, 0.3455624350895806)   (8.16, 0.8717525166469032)   
4        (1.36, 0.9988959030850687)    (1.6, 2.4474387205641235)   
...                             ...                          ...   
24978     (3.2, 0.9845865604368497)   (6.75, 2.6334983596069312)   
24979    (0.87, 0.5363709660408847)   (-8.93, 1.479600221938342)   
24980       (99.0, 0.9286121885545)     (nan, 2.421518059669553)   
24981   (-9.71, 0.8791418840636575)     (nan, 2.278767216306458)   
24982    (99.0, 1.0950552585569429)   (7.33, 2.8340965119582093)   

                                   6                             7   \
0      (-9.85, -0.032767202061978216)  (4.17, -0.28490658072142705)   
1      (-0.73, -0.024677744625034137)  (-5.34, -0.1122772237227956)   
2        (9.03, -0.16627984551732714)   (99.0, -0.7020357748306902)   
3       (-2.82, -0.04407747047395029)  (6.21, -0.16216211939170325)   
4        (7.04, -0.16036972135600372)   (4.61, -0.4478422525967419)   
...                               ...                           ...   
24978   (-8.79, -0.05752918873168249)  (-0.53, -0.5052155991951269)   
24979   (99.0, -0.010898819152827924)  (5.78, -0.28819390117979526)   
24980     (6.7, -0.08257020734209324)  (-6.75, -0.4585317315817452)   
24981    (4.56, -0.08442282232840581)  (-8.3, -0.43013804782163906)   
24982    (2.33, -0.10712368305149271)   (4.56, -0.5345301198953286)   

                                   8                            9   ...  \
0       (-8.98, -0.07522075795297471)  (-4.76, 1.0988320978465675)  ...   
1        (8.88, -0.03763307805907959)   (9.22, 0.4408206308280367)  ...   
2         (nan, -0.24344248656579123)     (nan, 2.764247921321048)  ...   
3          (nan, -0.0600822079735076)   (1.84, 0.6422618530261458)  ...   
4        (-0.44, -0.1921710877306323)    (5.73, 1.799311149890059)  ...   
...                               ...                          ...  ...   
24978   (-8.74, -0.13299546880148855)   (7.23, 1.9481421289663776)  ...   
24979  (-8.11, -0.060980450857713094)     (4.9, 1.096783780166937)  ...   
24980     (nan, -0.14132246109235533)    (nan, 1.7882

## (MSE) of the trained latent factors model on the validation set.

In [ ]:
original_data = arr
assert len(idx[0]) == len(idx[1])
validation_size = len(idx[0])
errors = []
for i in range(validation_size):
  user_id = idx[0][i]
  joke_id = idx[1][i]
  prediction_rating = predict_rating(user_id, joke_id)
  real_rating = original_data[user_id][joke_id]
  error = prediction_rating - real_rating
  errors.append(error)
mse = (np.array(errors) ** 2).mean()
print('Validation MSE:', mse)

# the test set.

In [ ]:
filled_data = np.zeros(original_data.shape)
rows, columns = original_data.shape
for user_id in range(rows):
  for joke_id in range(columns):
    if original_data[user_id][joke_id] == 99:
      filled_data[user_id][joke_id] = predict_rating(user_id, joke_id)
    else:
      filled_data[user_id][joke_id] = original_data[user_id][joke_id]

### Quiz

In [ ]:
# import pandas as pd
# import numpy as np
# # Your code here
# df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',header=None)
# df = df.iloc[:,1:]
# df.replace(99,np.nan,inplace=True)

In [ ]:
# user_ratings = df.values

In [ ]:
# import numpy as np


# def sgd(iterations):
#     """ Iterate over all users and all items and train for 
#         a certain number of iterations
#     """
#     mse_history = []
#     for iteration in range(iterations):
#         error = []
        
#         ### YOUR CODE (inner loop) HERE
#         for user_id in range(latent_user_preferences.shape[0]):
#             for item_id in range(latent_item_features.shape[0]):
#                 rating = user_ratings[user_id][item_id]
#                 if not np.isnan(rating):
#                     err = train(user_id, item_id, rating)
#                     error.append(err)
                    
#         mse = np.nanmean((np.array(error) ** 2))  
#         if (iteration % 10) == 0:
#             print('Iteration %d/%d:    MSE=%.3f' % (iteration, iterations, mse))
#             mse_history.append(mse)
    # return mse_history

In [ ]:
# np.random.seed(20)

# n_latent_factors = 2
# latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
# latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
# hist = sgd(100)

Iteration 0/100:    MSE=26.087
Iteration 10/100:    MSE=23.022
Iteration 20/100:    MSE=21.127
Iteration 30/100:    MSE=18.841
Iteration 40/100:    MSE=17.420
Iteration 50/100:    MSE=17.207
Iteration 60/100:    MSE=17.154
Iteration 70/100:    MSE=17.137


In [176]:
row = 19118
col = 2
df.iloc[row-1 , col-1]

7.86

In [100]:
items = pd.read_excel('movies_latent_factors.xlsx',sheet_name='Items')

In [101]:
users = pd.read_excel('movies_latent_factors.xlsx',sheet_name='Users')

In [102]:
items.head()

Movie ID                                              Title   Factor1  \
0        11          Star Wars: Episode IV - A New Hope (1977) -1.521848   
1        12                                Finding Nemo (2003) -0.342185   
2        13                                Forrest Gump (1994) -2.240888   
3        14                             American Beauty (1999) -0.634531   
4        22  Pirates of the Caribbean: The Curse of the Bla...  0.517348   

    Factor2   Factor3   Factor4   Factor5   Factor6   Factor7   Factor8  \
0 -1.038507  2.027269  0.247933 -0.594548  2.513260 -1.848910  0.476710   
1 -0.296586 -0.385962  2.443297 -1.097015 -0.619465  0.572887  0.329516   
2 -0.438815 -2.275177  0.614548  0.904469  0.711919 -0.420876  1.302036   
3  2.186059 -0.066681  0.086197  0.517558 -0.185319 -0.412352  0.063841   
4 -1.456763  0.369161  0.073903 -0.098332 -0.594722  0.828888  0.033626   

    Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  Factor15  
0 -0.224146 -0.760681 -0.973915  0.862379  0.403861  1.129616 -0.248806  
1 -0.712228  0.323554 -0.561948 -0.142405 -0.564415  0.506876  1.274993  
2 -0.868418 -0.160122  0.633667  0.133138 -0.330276 -2.209004 -0.419092  
3  0.075937 -0.577682  0.526803 -1.465557 -0.819682  0.549010 -0.681191  
4 -0.707414  0.717877  1.394326 -0.786986  1.429191  0.855746 -2.292566

In [103]:
users.head()

User   Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
0  4768 -0.204024  0.161079 -0.090447  0.138495 -0.162934  0.163894  0.051502   
1   156 -0.189652 -0.178979 -0.091490 -0.000823 -0.032646  0.177209 -0.098123   
2  5323 -0.115308 -0.090886 -0.053129  0.018472 -0.068081 -0.004828  0.113005   
3   174 -0.227462 -0.272532 -0.017231  0.054324  0.214755 -0.072639 -0.033122   
4  4529 -0.014616 -0.102218 -0.107935  0.155784 -0.123362 -0.118228 -0.013549   

    Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
0 -0.088582  0.126829  0.065967  0.085008  0.355404  0.007108 -0.118663   
1 -0.068283 -0.011575  0.120866 -0.009931 -0.048606  0.045916  0.113671   
2  0.102107  0.034758  0.000693 -0.073712 -0.019460  0.108372  0.054471   
3 -0.086508 -0.131479  0.180403  0.095890 -0.082396  0.036767 -0.165438   
4 -0.050622  0.058698 -0.159600 -0.142382 -0.132836 -0.039897  0.129063   

   Factor15  
0 -0.039125  
1  0.179873  
2 -0.109552  
3  0.050692  
4  0.102669

In [177]:
items[items['Movie ID'] == 36657]['Factor6']

97   -0.973154
Name: Factor6, dtype: float64

In [112]:
items['Factor7'].idxmin(),items['Factor7'].min()

(79, -2.001102294272314)

In [179]:
items['Factor1'].idxmax(),items['Factor1'].max()

(86, 4.023814610272081)

In [180]:
items.iloc[86,:]

Movie ID                       4327
Title       Charlie's Angels (2000)
Factor1                    4.023815
Factor2                    0.882963
Factor3                    1.138274
Factor4                   -0.431058
Factor5                    0.208086
Factor6                   -0.853887
Factor7                   -0.590821
Factor8                    0.416106
Factor9                     0.38739
Factor10                   0.522155
Factor11                  -0.379812
Factor12                  -0.567725
Factor13                  -1.007534
Factor14                   0.794589
Factor15                  -2.247246
Name: 86, dtype: object

In [137]:
users[users['User'] == 4768].iloc[:,1:].values

array([[-0.20402409,  0.16107871, -0.0904475 ,  0.13849453, -0.16293366,
         0.1638944 ,  0.05150182, -0.08858222,  0.126829  ,  0.06596709,
         0.08500812,  0.35540448,  0.007108  , -0.1186634 , -0.03912536]])

In [156]:
def predict_rating(user, item):
  """ Predict a rating """
  user_values = users[users['User'] == user].iloc[:,1:].values
  item_values = items[items['Movie ID'] == item].iloc[:,2:].values
  return user_values.dot(np.transpose(item_values))[0][0]


In [181]:
user = 3878
item = 10020
predict_rating(user, item)

0.12930619034729204

In [183]:
user = 783
item = 664
predict_rating(user, item)

-0.2042891885325195

In [170]:
user = 3878
ratings = []
for row in range(len(items)):
  item_id = (items.iloc[row,0])
  r = predict_rating(user, item_id)
  ratings.append(r)


In [171]:
np.array(ratings)

array([ 6.19344289e-01,  3.96214053e-01,  2.05783903e-01, -7.84492732e-02,
       -6.86051968e-01,  2.21596664e-01,  7.34459876e-02,  1.54849873e-01,
        4.23937185e-01,  7.74292199e-01,  1.36075867e-01,  9.28982787e-01,
        3.26437210e-01, -6.53104828e-02, -1.99243282e+00, -2.06115001e+00,
       -1.98016804e+00,  1.36740227e-01,  1.99943831e-01, -5.59330427e-01,
       -1.30809249e-01,  8.44621440e-01,  3.21202545e-02, -2.48359887e-01,
       -1.13856770e-01, -1.38316511e-01,  3.69218542e-02,  4.17017992e-01,
        7.02340327e-02,  1.00538903e-02,  6.04942393e-01,  3.37497508e-01,
        3.62405646e-01,  5.58140657e-01,  6.31850992e-01,  8.17604171e-01,
        3.95572818e-02, -1.07795320e+00,  3.45319212e-01, -1.19407699e-01,
       -1.97429618e-01,  5.52431258e-01, -6.80479610e-01, -1.00238852e+00,
        2.15949674e-01, -1.16421041e-01,  1.30240200e-01, -1.26943274e-01,
        3.87590826e-01,  3.07874513e-01, -3.09976232e-01, -1.79201248e+00,
       -3.03905917e-02,  

In [172]:
np.sort(np.array(ratings))

array([-2.06115001e+00, -1.99243282e+00, -1.98016804e+00, -1.79201248e+00,
       -1.23451297e+00, -1.07795320e+00, -1.00238852e+00, -9.66949811e-01,
       -8.00315450e-01, -6.86051968e-01, -6.80479610e-01, -5.59330427e-01,
       -5.55635620e-01, -4.30571644e-01, -3.85048438e-01, -3.76226986e-01,
       -3.37117752e-01, -3.09976232e-01, -2.56986911e-01, -2.48359887e-01,
       -1.97429618e-01, -1.80673393e-01, -1.77105192e-01, -1.44503042e-01,
       -1.38316511e-01, -1.37199165e-01, -1.30809249e-01, -1.26943274e-01,
       -1.19407699e-01, -1.16421041e-01, -1.13856770e-01, -9.38850946e-02,
       -9.21997005e-02, -8.45814680e-02, -7.84492732e-02, -6.53104828e-02,
       -6.05956766e-02, -4.36375511e-02, -3.03905917e-02, -1.87043467e-02,
       -6.43111172e-03, -8.28610630e-04,  1.00538903e-02,  2.02102325e-02,
        3.21202545e-02,  3.69218542e-02,  3.95572818e-02,  4.29220331e-02,
        5.12009984e-02,  7.02340327e-02,  7.14742358e-02,  7.34459876e-02,
        7.92471995e-02,  

In [173]:
np.argsort(np.array(ratings))

array([15, 14, 16, 51, 86, 37, 43, 79, 72,  4, 42, 19, 98, 66, 56, 97, 81,
       50, 93, 23, 40, 58, 88, 71, 25, 57, 20, 47, 39, 45, 24, 61, 62, 94,
        3, 13, 80, 65, 52, 92, 82, 89, 29, 84, 22, 26, 36, 76, 68, 28, 63,
        6, 55, 96, 46, 10, 17,  7, 75, 83, 99, 18,  2, 44, 69,  5, 74, 60,
       67, 54, 49, 12, 31, 38, 32, 95, 87, 48,  1, 91, 64, 27,  8, 78, 53,
       73, 41, 33, 77, 59, 30,  0, 34, 85, 70,  9, 35, 21, 90, 11])

In [174]:
np.array(ratings)[11]

0.9289827867793357

In [175]:
items.iloc[10,1]

'Gladiator (2000)'