In [ ]:
# Machine learning models require all input and output variables to be numeric.

# This means that if your data contains categorical data, you must encode it to numbers before you can fit and evaluate a model.

# ordinal encoding for categorical variables that have a natural rank ordering
# one-hot encoding for categorical variables that do not have a natural rank

# a numerical variable between 1 and 10 can be divided into an ordinal variable with 5 labels with an ordinal relationship: 1-2, 3-4, 5-6, 7-8, 9-10. This is called discretization.

In [14]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder as en

In [20]:
a = np.array([["red"], ["green"], ["blue"]])

en().fit_transform(a)

array([[2.],
       [1.],
       [0.]])

In [6]:
from sklearn.preprocessing import OneHotEncoder as en

en(sparse=False).fit_transform(a)

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
en(drop="first", sparse=False).fit_transform(
    a
)  # first column dropped from alphabatecal order

array([[0., 1.],
       [1., 0.],
       [0., 0.]])

In [24]:
from sklearn.preprocessing import LabelEncoder as en  # for output variables

en().fit_transform(["y", "n", "y"])

array([1, 0, 1], dtype=int64)