In [1]:
import data

Text Cleansing <br>
removal of extra whitespace and add space around punctuation marks.
removal of special characters

In [3]:

sample_text = r"SELECT count(*) FROM head WHERE age>56"
data.Preprocess('sample').text_whitespace(sample_text).numpy()

b'SELECT count (  *  )  FROM head WHERE age > 56'

Standardization

The input and target sentences are converted into lower case and normalized using NFKD method by TensorFlow_Text library.

In [4]:
data.Preprocess('sample').text_standardize(sample_text).numpy()

b'select count(*) from head where age>56'

Append Sentence Start and End Tags <br>

Each input and target sentence is appended with '[START]' and '[END]' tags to mark the start and end of the sentence respectively

In [5]:
data.Preprocess('sample').add_SOS_EOS(sample_text).numpy()

b'[start] SELECT count(*) FROM head WHERE age>56 [end]'

Text Vectorization

In [2]:
sample_in= ['How many heads of the departments are older than 56 ?',
            'List the name, born state and age of the heads of departments ordered by age.']


In [3]:
sample_out = [r'SELECT count(*) FROM head WHERE age  >  56',
             r'SELECT name ,  born_state ,  age FROM head ORDER BY age']

In [4]:
print('Input Vectorizor created')
input_text_processor = data.Features().vectorizor(sample_in , 7000)
print('Output Vectorizor created')
output_text_processor = data.Features().vectorizor(sample_out , 7000)

print('Vocabulary size for Input', input_text_processor.vocabulary_size())
print('Vocabulary size for Output', output_text_processor.vocabulary_size())

Input Vectorizor created
Sample Vocabulary ['', '[UNK]', 'the', 'of', 'heads', 'departments', 'age', '[start]', '[end]', 'than']
Output Vectorizor created
Sample Vocabulary ['', '[UNK]', 'age', 'select', 'head', 'from', '[start]', '[end]', ',', 'where']
Vocabulary size for Input 25
Vocabulary size for Output 20


Vectorized and Padded Input created

In [9]:
input_text_processor(sample_in)

<tf.Tensor: shape=(2, 19), dtype=int64, numpy=
array([[ 7, 16, 14,  4,  3,  2,  5, 19, 12,  9, 22, 21,  8,  0,  0,  0,
         0,  0,  0],
       [ 7, 15,  2, 13, 24, 18, 10, 20,  6,  3,  2,  4,  3,  5, 11, 17,
         6, 23,  8]], dtype=int64)>

In [10]:
output_text_processor(sample_out)

<tf.Tensor: shape=(2, 13), dtype=int64, numpy=
array([[ 6,  3, 12, 19, 17, 18,  5,  4,  9,  2, 15, 16,  7],
       [ 6,  3, 11,  8, 14,  8,  2,  5,  4, 10, 13,  2,  7]], dtype=int64)>